%% Initialisation du workspace
clear variables;
close all;

%% Initialisation des variables
load('workspace.mat');
points_image = points_image_D;
clear points_image_G;
fichier_mire = 'img/vue droite0.png';

cube_vertices = [0 0 0; ...
    0 1 0; ...
    1 1 0; ...
    1 0 0; ...
    0 0 1; ...
    0 1 1; ...
    1 1 1; ...
    1 0 1]*2.5;

cube_faces = [1 2 3 4; ...
    2 6 7 3; ...
    4 3 7 8; ...
    1 5 8 4; ...
    1 2 6 5; ...
    5 6 7 8];

%% Résolution du problème
[ matrice_projection ] = calcul_matrice_projection_dlt( points_monde , points_image );
[ points_image_projete ] = projection_points( points_monde , matrice_projection );
[ erreur_projection ] = calcul_erreur_projection( points_image , points_image_projete );

%% Projection d'un cube
[ points_cube ] = projection_points( cube_vertices' , matrice_projection );
cube_new_vertices=vertcat(points_cube,ones(1,length(points_cube)));
imshow(fichier_mire);
patch('Faces',cube_faces,'Vertices',points_cube','FaceColor','b');